def Buttons(self):
        """Creates all buttons needed for a game of poker
        
        :param self: The QGraphicsView
        :type self: object
        """
        if self.game.turns() == 0:
            if self.player1.Role == "Dealer":
                self.vbox = QVBoxLayout()
                self.vbox.addStretch(2)
                self.Deal1 = QPushButton("Deal",self)
                self.Deal1.setFixedWidth(100)
                self.Deal1.clicked.connect(self.game.deal)
                self.Deal1.clicked.connect(self.showHand)
                self.Deal1.clicked.connect(self.OpponentButton)


                self.label1 = QLabel(f"{self.player1.name}'s money: {self.player1.Money}")
                self.label2 = QLabel(f"{self.player2.name}'s money: {self.player2.Money}")
                self.label3 = QLabel(f"Pot: {self.game.Pot}")
                self.vbox.addWidget(self.label3)
                self.vbox.addWidget(self.label1)
                self.vbox.addWidget(self.label2)
                self.vbox.addWidget(self.Deal1)
                self.setLayout(self.vbox)
        
        elif self.game.turns() == 1:
            self.vbox.removeWidget(self.Deal1)
            self.BigBlindBet = QPushButton("Bet big blind",self)
            self.BigBlindBet.setFixedWidth(100)
            self.BigBlindBet.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.BigBlindBet.clicked.connect(self.updateMoney)
        
        elif self.game.turns() == 2:
            self.vbox.removeWidget(self.BigBlindBet)
            self.BigBlindBet.deleteLater()

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.OpponentButton)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.CardsOnBoard)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.CardsOnBoard)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 3:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.OpponentButton)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 4:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()
    
            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player1))
            self.Check.clicked.connect(self.updateMoney)   
            self.Check.clicked.connect(self.FourthCard)
            self.Check.clicked.connect(self.OpponentButton) 

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.FourthCard)
            self.Call.clicked.connect(self.OpponentButton)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.FourthCard)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.FourthCard)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 5:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player1))
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 6:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player1))
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)
            self.Check.clicked.connect(self.River)
            self.Check.clicked.connect(self.showWinner)
            self.Check.clicked.connect(self.OpponentButton)

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.River)
            self.Call.clicked.connect(self.OpponentButton)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.River)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.River)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 7:
            self.vbox.removeWidget(self.Call)
            self.Call.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player1,20))
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.OpponentButton)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 8:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player1))
            self.Check.clicked.connect(self.showWinner)
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player1))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player1,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.showWinner)
            self.bet.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player1))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
    
    def OpponentButton(self):
        if self.game.turns() == 0:
            if self.player2.Role == "Dealer":
                self.vbox = QVBoxLayout()
                self.vbox.addStretch(2)
                self.Deal1 = QPushButton("Deal",self)
                self.Deal1.setFixedWidth(100)
                self.Deal1.clicked.connect(self.game.deal)
                self.Deal1.clicked.connect(self.showHand)

        elif self.game.turns() == 1:
            self.vbox.removeWidget(self.Deal1)
            self.Deal1.deleteLater()

            self.BigBlindBet = QPushButton("Bet big blind",self)
            self.BigBlindBet.setFixedWidth(100)
            self.BigBlindBet.clicked.connect(lambda: self.game.bet(self.player2,20))
            self.BigBlindBet.clicked.connect(self.updateMoney)
            self.BigBlindBet.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.BigBlindBet)
        
        elif self.game.turns() == 2:
            self.vbox.removeWidget(self.BigBlindBet)
            self.BigBlindBet.deleteLater()

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player2,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.CardsOnBoard)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.CardsOnBoard)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 3:
            self.vbox.removeWidget(self.Call)
            self.Call.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()
    
            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)

        elif self.game.turns() == 4:
            self.vbox.removeWidget(self.Call)
            self.Call.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)
            self.Check.clicked.connect(self.FourthCard)
            self.Check.clicked.connect(self.Buttons)
    
            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player2,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.FourthCard)
            self.Call.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.FourthCard)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.conenct(self.FourthCard)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 5:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Call)
            self.Call.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 6:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()
    
            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)
            self.Check.clicked.connect(self.River)
            self.Check.clicked.connect(self.showWinner)
            self.Check.clicked.connect(self.Buttons)

            self.Call = QPushButton("Call",self)
            self.Call.setFixedWidth(100)
            self.Call.clicked.connect(lambda: self.game.bet(self.player2,20))
            self.Call.clicked.connect(self.CardsOnBoard)
            self.Call.clicked.connect(self.updateMoney)
            self.Call.clicked.connect(self.FourthCard)
            self.Call.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.River)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.River)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Call)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)
        
        elif self.game.turns() == 7:
            self.vbox.removeWidget(self.Call)
            self.Call.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(self.Buttons)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player1,self.player2))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.Buttons)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.Buttons)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)

        elif self.game.turns() == 8:
            self.vbox.removeWidget(self.Check)
            self.Check.deleteLater()
            self.vbox.removeWidget(self.Fold)
            self.Fold.deleteLater()
            self.vbox.removeWidget(self.bet)
            self.vbox.removeWidget(self.betLine)
            self.bet.deleteLater()
            self.betLine.deleteLater()
            self.vbox.removeWidget(self.allIn)
            self.allIn.deleteLater()

            self.Check = QPushButton("Check",self)
            self.Check.setFixedWidth(100)
            self.Check.clicked.connect(lambda: self.game.check(self.player2))
            self.Check.clicked.connect(self.showWinner)
            self.Check.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.Check.clicked.connect(self.updateMoney)

            self.Fold = QPushButton("Fold",self)
            self.Fold.setFixedWidth(100)
            self.Fold.clicked.connect(lambda: self.game.fold(self.player2))
            self.Fold.clicked.connect(lambda: self.game.roundOver(self.player2,self.player1))
            self.Fold.clicked.connect(self.resetBoard)
            self.Fold.clicked.connect(self.updateMoney)

            self.betLine = QLineEdit(self)
            self.betLine.setFixedWidth(100)

            self.bet = QPushButton("Bet",self)
            self.bet.setFixedWidth(100)
            self.bet.clicked.connect(lambda: self.game.bet(self.player2,int(self.betLine.text())))
            self.bet.clicked.connect(self.updateMoney)
            self.bet.clicked.connect(self.showWinner)
            self.bet.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.bet.clicked.connect(self.OpponentButton)

            self.allIn = QPushButton("All in",self)
            self.allIn.setFixedWidth(100)
            self.allIn.clicked.connect(lambda: self.game.Allin(self.player2))
            self.allIn.clicked.connect(self.updateMoney)
            self.allIn.clicked.connect(self.showWinner)
            self.allIn.clicked.connect(lambda: self.game.determineWinner(self.player1,self.player2))
            self.allIn.clicked.connect(self.OpponentButton)

            self.vbox.addWidget(self.Check)
            self.vbox.addWidget(self.Fold)
            self.vbox.addWidget(self.bet)
            self.vbox.addWidget(self.betLine)
            self.vbox.addWidget(self.allIn)